# Generated by Django 4.1.5 on 2023-01-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Фреймворк',
                'verbose_name_plural': 'Фреймворки',
            },
        ),
    ]
