# Generated by Django 4.1.5 on 2023-01-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Фреймворк',
                'verbose_name_plural': 'Фреймворки',
            },
        ),
    ]
