# Generated by Django 4.1.5 on 2023-01-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
